<option value="" <?php if ($province=="") echo "selected"; ?> >Seleziona</option>
<option value="AG" <?php if ($province=="AG") echo "selected"; ?> >Agrigento</option>
<option value="AL" <?php if ($province=="AL") echo "selected"; ?> >Alessandria</option>
<option value="AN" <?php if ($province=="AN") echo "selected"; ?> >Ancona</option>
<option value="AO" <?php if ($province=="AO") echo "selected"; ?> >Aosta</option>
<option value="AR" <?php if ($province=="AR") echo "selected"; ?> >Arezzo</option>
<option value="AP" <?php if ($province=="AP") echo "selected"; ?> >Ascoli Piceno</option>
<option value="AT" <?php if ($province=="AT") echo "selected"; ?> >Asti</option>
<option value="AV" <?php if ($province=="AV") echo "selected"; ?> >Avellino</option>
<option value="BA" <?php if ($province=="BA") echo "selected"; ?> >Bari</option>
<option value="BL" <?php if ($province=="BL") echo "selected"; ?> >Belluno</option>
<option value="BN" <?php if ($province=="BN") echo "selected"; ?> >Benevento</option>
<option value="BG" <?php if ($province=="BG") echo "selected"; ?> >Bergamo</option>
<option value="BI" <?php if ($province=="BI") echo "selected"; ?> >Biella</option>
<option value="BO" <?php if ($province=="BO") echo "selected"; ?> >Bologna</option>
<option value="BZ" <?php if ($province=="BZ") echo "selected"; ?> >Bolzano</option>
<option value="BS" <?php if ($province=="BS") echo "selected"; ?> >Brescia</option>
<option value="BR" <?php if ($province=="BR") echo "selected"; ?> >Brindisi</option>
<option value="CA" <?php if ($province=="CA") echo "selected"; ?> >Cagliari</option>
<option value="CL" <?php if ($province=="CL") echo "selected"; ?> >Caltanissetta</option>
<option value="CB" <?php if ($province=="CB") echo "selected"; ?> >Campobasso</option>
<option value="CE" <?php if ($province=="CE") echo "selected"; ?> >Caserta</option>
<option value="CT" <?php if ($province=="CT") echo "selected"; ?> >Catania</option>
<option value="CZ" <?php if ($province=="CZ") echo "selected"; ?> >Catanzaro</option>
<option value="CH" <?php if ($province=="CH") echo "selected"; ?> >Chieti</option>
<option value="CO" <?php if ($province=="CO") echo "selected"; ?> >Como</option>
<option value="CS" <?php if ($province=="CS") echo "selected"; ?> >Cosenza</option>
<option value="CR" <?php if ($province=="CR") echo "selected"; ?> >Cremona</option>
<option value="KR" <?php if ($province=="KR") echo "selected"; ?> >Crotone</option>
<option value="CN" <?php if ($province=="CN") echo "selected"; ?> >Cuneo</option>
<option value="EN" <?php if ($province=="EN") echo "selected"; ?> >Enna</option>
<option value="FE" <?php if ($province=="FE") echo "selected"; ?> >Ferrara</option>
<option value="FI" <?php if ($province=="FI") echo "selected"; ?> >Firenze</option>
<option value="FG" <?php if ($province=="FG") echo "selected"; ?> >Foggia</option>
<option value="FO" <?php if ($province=="FO") echo "selected"; ?> >Forl&igrave; - Cesena</option>
<option value="FR" <?php if ($province=="FR") echo "selected"; ?> >Frosinone</option>
<option value="GE" <?php if ($province=="GE") echo "selected"; ?> >Genova</option>
<option value="GO" <?php if ($province=="GO") echo "selected"; ?> >Gorizia</option>
<option value="GR" <?php if ($province=="GR") echo "selected"; ?> >Grosseto</option>
<option value="IM" <?php if ($province=="IM") echo "selected"; ?> >Imperia</option>
<option value="IS" <?php if ($province=="IS") echo "selected"; ?> >Isernia</option>
<option value="SP" <?php if ($province=="SP") echo "selected"; ?> >La Spezia</option>
<option value="AQ" <?php if ($province=="AQ") echo "selected"; ?> >L'Aquila</option>
<option value="LT" <?php if ($province=="LT") echo "selected"; ?> >Latina</option>
<option value="LE" <?php if ($province=="LE") echo "selected"; ?> >Lecce</option>
<option value="LC" <?php if ($province=="LC") echo "selected"; ?> >Lecco</option>
<option value="LI" <?php if ($province=="LI") echo "selected"; ?> >Livorno</option>
<option value="LO" <?php if ($province=="LO") echo "selected"; ?> >Lodi</option>
<option value="LU" <?php if ($province=="LU") echo "selected"; ?> >Lucca</option>
<option value="MC" <?php if ($province=="MC") echo "selected"; ?> >Macerata</option>
<option value="MN" <?php if ($province=="MN") echo "selected"; ?> >Mantova</option>
<option value="MS" <?php if ($province=="MS") echo "selected"; ?> >Massa Carrara</option>
<option value="MT" <?php if ($province=="MT") echo "selected"; ?> >Matera</option>
<option value="ME" <?php if ($province=="ME") echo "selected"; ?> >Messina</option>
<option value="MI" <?php if ($province=="MI") echo "selected"; ?> >Milano</option>
<option value="MO" <?php if ($province=="MO") echo "selected"; ?> >Modena</option>
<option value="NA" <?php if ($province=="NA") echo "selected"; ?> >Napoli</option>
<option value="NO" <?php if ($province=="NO") echo "selected"; ?> >Novara</option>
<option value="NU" <?php if ($province=="NU") echo "selected"; ?> >Nuoro</option>
<option value="OR" <?php if ($province=="OR") echo "selected"; ?> >Oristano</option>
<option value="PD" <?php if ($province=="PD") echo "selected"; ?> >Padova</option>
<option value="PA" <?php if ($province=="PA") echo "selected"; ?> >Palermo</option>
<option value="PR" <?php if ($province=="PR") echo "selected"; ?> >Parma</option>
<option value="PV" <?php if ($province=="PV") echo "selected"; ?> >Pavia</option>
<option value="PG" <?php if ($province=="PG") echo "selected"; ?> >Perugia</option>
<option value="PS" <?php if ($province=="PS") echo "selected"; ?> >Pesaro</option>
<option value="PE" <?php if ($province=="PE") echo "selected"; ?> >Pescara</option>
<option value="PC" <?php if ($province=="PC") echo "selected"; ?> >Piacenza</option>
<option value="PI" <?php if ($province=="PI") echo "selected"; ?> >Pisa</option>
<option value="PT" <?php if ($province=="PT") echo "selected"; ?> >Pistoia</option>
<option value="PN" <?php if ($province=="PN") echo "selected"; ?> >Pordenone</option>
<option value="PZ" <?php if ($province=="PZ") echo "selected"; ?> >Potenza</option>
<option value="PO" <?php if ($province=="PO") echo "selected"; ?> >Prato</option>
<option value="RG" <?php if ($province=="RG") echo "selected"; ?> >Ragusa</option>
<option value="RA" <?php if ($province=="RA") echo "selected"; ?> >Ravenna</option>
<option value="RC" <?php if ($province=="RC") echo "selected"; ?> >Reggio Calabria</option>
<option value="RE" <?php if ($province=="RE") echo "selected"; ?> >Reggio Emilia</option>
<option value="RI" <?php if ($province=="RI") echo "selected"; ?> >Rieti</option>
<option value="RN" <?php if ($province=="RN") echo "selected"; ?> >Rimini</option>
<option value="RM" <?php if ($province=="RM") echo "selected"; ?> >Roma</option>
<option value="RO" <?php if ($province=="RO") echo "selected"; ?> >Rovigo</option>
<option value="SA" <?php if ($province=="SA") echo "selected"; ?> >Salerno</option>
<option value="SS" <?php if ($province=="SS") echo "selected"; ?> >Sassari</option>
<option value="SV" <?php if ($province=="SV") echo "selected"; ?> >Savona</option>
<option value="SI" <?php if ($province=="SI") echo "selected"; ?> >Siena</option>
<option value="SR" <?php if ($province=="SR") echo "selected"; ?> >Siracusa</option>
<option value="SO" <?php if ($province=="SO") echo "selected"; ?> >Sondrio</option>
<option value="TA" <?php if ($province=="TA") echo "selected"; ?> >Taranto</option>
<option value="TE" <?php if ($province=="TE") echo "selected"; ?> >Teramo</option>
<option value="TR" <?php if ($province=="TR") echo "selected"; ?> >Terni</option>
<option value="TO" <?php if ($province=="TO") echo "selected"; ?> >Torino</option>
<option value="TP" <?php if ($province=="TP") echo "selected"; ?> >Trapani</option>
<option value="TN" <?php if ($province=="TN") echo "selected"; ?> >Trento</option>
<option value="TV" <?php if ($province=="TV") echo "selected"; ?> >Treviso</option>
<option value="TS" <?php if ($province=="TS") echo "selected"; ?> >Trieste</option>
<option value="UD" <?php if ($province=="UD") echo "selected"; ?> >Udine</option>
<option value="VA" <?php if ($province=="VA") echo "selected"; ?> >Varese</option>
<option value="VE" <?php if ($province=="VE") echo "selected"; ?> >Venezia</option>
<option value="VB" <?php if ($province=="VB") echo "selected"; ?> >Verbania-Cusio-Ossola</option>
<option value="VC" <?php if ($province=="VC") echo "selected"; ?> >Vercelli</option>
<option value="VR" <?php if ($province=="VR") echo "selected"; ?> >Verona</option>
<option value="VV" <?php if ($province=="VV") echo "selected"; ?> >Vibo Valentia</option>
<option value="VI" <?php if ($province=="VI") echo "selected"; ?> >Vicenza</option>
<option value="VT" <?php if ($province=="VT") echo "selected"; ?> >Viterbo</option>
